### ISSUE TITLE
Android M changed logcat output => no logs displayed

### ISSUE THREAD

**Issue by Groxx** [JakeWharton/pidcat#102]
On the M preview 1, with a Nexus 6:
Alas more changes :|  It seems to use the same "Start proc" format as 5.1, but the (default) columns have changed.

An example log line:
`06-06 12:14:46.355   372 18641 D audio_hw_primary: disable_audio_route: reset and update mixer path: audio-record`

Regex + group changes that fix output:
`LOG_LINE  = re.compile(r'^\S+\s\S+\s+(\d+)\s+\S+\s([A-Z])\s([^:]+)\s(.+)$')`
`owner, level, tag, message = log_line.groups()`

Not sure how you'd like to fit them in with the existing code (if you have any intention of fixing this for preview releases), but I figured I'd at least try to save some effort :)

**Comment by Groxx** [comment]
Hm.  There might be other problems too.  Sometimes it displays crashing errors, sometimes it does not, even though they're all under the right pid.  I'll look into it more when I have some time...

**Comment by GBouerat** [comment]
On Android Marshmallow 
```
adb logcat
```

default output format is "threadtime" instead of "brief" on prior versions

http://developer.android.com/tools/debugging/debugging-log.html#outputFormat

**Comment by GBouerat** [comment]
On Android Marshmallow, you can use pidcat like this

```
adb logcat -v brief | pidcat
```

**Comment by JakeWharton** [comment]
This is already fixed on `master` (and has been for some time). I was just waiting until the final M release before I released pidcat in case it changed. Now that it has been released, I'll work on a pidcat release sometime this week!

**Comment by paleozogt** [comment]
did this ever get released? all i see in releases is v2.0.0 on May 25, 2015

**Comment by JakeWharton** [comment]
Not yet, no. A lot going on. There's instructions for installing from
master in the README.

**Comment by Binghammer** [comment]
I know this is closed, but I am seeing the problem again. I can fix it by using `adb logcat -v brief | pidcat` as stated above.

**Comment by AndreSand** [comment]
Same issue. 
Resolve with: `adb logcat -v brief | pidcat com.myPackage`

**Comment by sdrygalski** [comment]
This should be in the readme, I read all issues before I found solution how to use this library.
