### ISSUE TITLE
Wrapped lines being split with newlines

### ISSUE THREAD

**Issue by dimsuz** [JakeWharton/pidcat#103]
It seems that pidcat breaks wrapped lines from logcat by inserting a "\n"-s.
This is not an issue most of the time, but when I have some log output which contains a long url - and then try to select those multiple lines in the terminal and copy them to clipboard, this gets broken because instead of "http://somereallylongurl.com" I get 
```
http://somer
eallylong
url
```

**Comment by JakeWharton** [comment]
This seems unsolvable with the current design. Lines are manually wrapped and indented to maintain the content to the right of the tag and log level for visual simplicity. Without this the wrapped lines would start from the left of the screen and clash with these other elements.

See the "Volley" line below:
![](https://raw.githubusercontent.com/JakeWharton/pidcat/master/screen.png)

**Comment by dimsuz** [comment]
I see, makes sense.
