### ISSUE TITLE
Pidcat doesn't seem to be working with my Nexus 6P

### ISSUE THREAD

**Issue by loeschg** [JakeWharton/pidcat#117]
Running on OS X 10.11.1 in iTerm2 connected to a Nexus 6P

**Issue**: `pidcat` doesn't output anything

STR:
- Connect 6P
- Run `pidcat`

Interesting things to note (maybe):
- `adb logcat` does have expected output
- when I disconnect my device after starting pidcat, the `pidcat` process automatically stops. It seems to recognize there's a device attached.
- `adb devices` shows that the device is recognized

**Comment by JakeWharton** [comment]
Are you using the code on master?

**Comment by loeschg** [comment]
from homebrew

**Comment by JakeWharton** [comment]
See the REAMDE for installing the development version. This has been fixed
but not released.

**Comment by loeschg** [comment]
:+1: Thanks for the quick response! Will give that a go and report back if I have any issues.
