### ISSUE TITLE
Does not work with emulator

### ISSUE THREAD

**Issue by trulex** [JakeWharton/pidcat#129]
```
$ adb devices 
List of devices attached
emulator-5554   device
```

> adb logcat

works, but when I run
>pidcat

nothing happens.

My OS is Arch Linux.

**Comment by JakeWharton** [comment]
Have you tried the version on `master`?

**Comment by trulex** [comment]
Status on master branch:
it works, but output is not colored, looks like color tags are not properly parsed
>b'\x1b[35m ...
b'\x1b[36m ...

Also when package argument is provided, nothing is printed out.

**Comment by awendland** [comment]
Using the latest source from master allows me to use pidcat with the emulator. @JakeWharton, will you be releasing a new version soon? It would be nice to be able to just use `brew install pidcat` and have it work.

**Comment by JakeWharton** [comment]
Yes

**Comment by burntcookie90** [comment]
@trulex the aur package patches it to use the `python2` binary on arch.
