### ISSUE TITLE
Is this works on OSX Sierra?

### ISSUE THREAD

**Issue by hendrawd** [JakeWharton/pidcat#136]
I downloaded it and tried to run it with package name, but nothing happens.
When i use --version, it shows the version though

**Comment by JakeWharton** [comment]
It works for me. Is `adb` on your path?

**Comment by hendrawd** [comment]
Yes it is. My logcat is running too. Will it cause the problem?

**Comment by hendrawd** [comment]
![screen shot 2016-12-16 at 11 06 59 am](https://cloud.githubusercontent.com/assets/9481791/21251300/5a5745d8-c37f-11e6-8581-3bc0dd20f1b2.png)

**Comment by hendrawd** [comment]
I tried to my friend's iMac with OSX Sierra too, there is no problem. So the problem is just because of my machine. I will try to find the problem. Thank you for your response @JakeWharton

**Comment by LiHanGuang** [comment]
@hendrawd 

The python version is  2.7?  need 3.x ?
