### ISSUE TITLE
Log tags get truncated 

### ISSUE THREAD

**Issue by karimfikani** [JakeWharton/pidcat#138]
Here is a screenshot of what is showing:

![screen shot 2017-01-17 at 10 32 22 am](https://cloud.githubusercontent.com/assets/2486075/22034261/8f82a9fc-dca0-11e6-91e3-9a38b56de54e.png)

You can see some of the tags are truncated for example "adRemoteFolderOperation" is actually "ReadRemoteFolderOperation".

**Comment by JakeWharton** [comment]
Android's limit is 23 characters and that's the default limit here as well.

**Comment by karimfikani** [comment]
Ok got it thx
