### ISSUE TITLE
Read  from  .log file 

### ISSUE THREAD

**Issue by pusabless** [JakeWharton/pidcat#156]
the tool is powerful.
but could it support read from a log file

**Comment by JakeWharton** [comment]
You can pipe into it like `cat log.txt | pidcat` and it will work.

**Comment by pusabless** [comment]
> You can pipe into it like `cat log.txt | pidcat` and it will work.

![image](https://user-images.githubusercontent.com/25945400/83477537-0d30c000-a4c6-11ea-8bc2-66b9bab1f069.png)
I use adb logcat >> test.log  and test the cmd , but it can not print any line .
