### ISSUE TITLE
--current : TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by nrvale0** [JakeWharton/pidcat#172]
When using --current, I get the following:

    $ pidcat --current
    Traceback (most recent call last):
      File "/usr/bin/pidcat", line 66, in <module>
        running_package_name = re.search(".*TaskRecord.*A[= ]([^ ^}]*)", system_dump).group(1)
      File "/usr/lib/python3.8/re.py", line 201, in search
        return _compile(pattern, flags).search(string)
    TypeError: cannot use a string pattern on a bytes-like object

regardless of app.

Host OS: 

    $ cat /etc/issue
    Pop!_OS 20.10 \n \l

Python:

    $ python3 --version
    Python 3.8.6

Package:
    
    $ dpkg -l pidcat
    Desired=Unknown/Install/Remove/Purge/Hold
    | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
    |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
    ||/ Name           Version      Architecture Description
    +++-==============-============-============-================================>
    ii  pidcat         2.1.0-4      all

Device:  
  
    $ adb devices -l
    List of devices attached
    894Y03RMF              device usb:1-1 product:aosp_crosshatch model:Pixel_3_XL device:crosshatch transport_id:2
  
    $ adb shell getprop | grep -i ro.build | egrep -v id
    [ro.build.ab_update]: [true]
    [ro.build.characteristics]: [nosdcard]
    [ro.build.date]: [Tue Jan  5 03:08:09 UTC 2021]
    [ro.build.date.utc]: [1609816089]
    [ro.build.flavor]: [aosp_crosshatch-user]
    [ro.build.host]: [grapheneos]
    [ro.build.product]: [crosshatch]
    [ro.build.tags]: [release-keys]
    [ro.build.type]: [user]
    [ro.build.user]: [grapheneos]
    [ro.build.version.all_codenames]: [REL]
    [ro.build.version.base_os]: []
    [ro.build.version.codename]: [REL]
    [ro.build.version.incremental]: [2021.01.05.03]
    [ro.build.version.min_supported_target_sdk]: [28]
    [ro.build.version.preview_sdk]: [0]
    [ro.build.version.preview_sdk_fingerprint]: [REL]
    [ro.build.version.release]: [11]
    [ro.build.version.release_or_codename]: [11]
    [ro.build.version.sdk]: [30]
    [ro.build.version.security_patch]: [2021-01-05]

**Comment by guoxiao** [comment]
Same issue in Python3

**Comment by ramanr1** [comment]
I got it working by making this change in pidcat.py 

Line 66 
` running_package_name = re.search(".*TaskRecord.*A[= ]([^ ^}]*)", **_str(_**system_dump)**_)_**.group(1)`
