### ISSUE TITLE
TypeError: can't use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by delor** [JakeWharton/pidcat#18]
system: Arch Linux 3.9.6-1 x86_64
Python version: 3.3.2
pidcat version: f624fe4b224f65379fee317c6ee92af0e3447d12

```
Traceback (most recent call last):
  File ".bin/pidcat.py", line 173, in <module>
    bug_line = BUG_LINE.match(line)
TypeError: can't use a string pattern on a bytes-like object
```

**Comment by bj0** [comment]
You also can't mix bytes and string objects in regex, so line 66 throws the same exception.

Also, why do you `.encode` the output before you print it?  For me that prevents the output from printing correctly, it looks like this:
  > b'\x1b[33m      PeopleDataManager\x1b[0m \x1b[30;102m I \x1b[0m removeNotification'

I'm using Python 3.6, and removing the `encode` part of line 360 makes it print correctly
