### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by mathieudebrito** [JakeWharton/pidcat#46]
Hey Jake, 

I'm on a macbook pro, python installed.
I installed pidcat via brew, everything seemed to work fine.
But when I want to launch pidcat, I have this error (OSError: [Errno 2] No such file or directory).

I'm not sure if it's something from pidcat or my computer. I asked Google but it couldn't give any good answer.... so...

Do you have any idea ?

mathieu$ pidcat com.mdb.android.russianroulette
Traceback (most recent call last):
  File "/usr/local/bin/pidcat", line 150, in <module>
    adb = subprocess.Popen(adb_command, stdin=PIPE, stdout=PIPE, stderr=PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 711, in **init**
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by tomwijgers** [comment]
For anyone coming across this with the same issue as me, make sure when setting your PATH that it uses an absolute path, no ~/

**Comment by danielgomezrico** [comment]
No relative paths worked for me too.

**Comment by ol-v-er** [comment]
I had to modify my ~/pathToAndroidLibrary by /Users/mylogin/pathToAndroidLibrary and it works. @tomwijgers you were right!
