### ISSUE TITLE
Android Studio integration

### ISSUE THREAD

**Issue by IgorGanapolsky** [JakeWharton/pidcat#91]
Hello, is there a way to integrate pidcat into Android Studio automtically (instead of built-in logcat)?

**Comment by JakeWharton** [comment]
No. You can stop logcat from showing in AS but unchecking "Show logcat automatically" in the run configuration though.

![screen shot 2015-02-24 at 11 09 15 am](https://cloud.githubusercontent.com/assets/66577/6356928/a7f79a4a-bc15-11e4-96b2-f3420087597c.png)
