### ISSUE TITLE
Pidcat doesn't show logs on Python 3

### ISSUE THREAD

**Issue by rynkowsg** [JakeWharton/pidcat#97]
I use by default Python 3.4.3 and pidcat doesn't print logs.
When I ran it on Python 2, it works.

**Comment by diVineProportion** [comment]
works fine in python 3.9.x you just have to edit the last line.. 

diff```
--  print(linebuf.encode('utf-8'))
++  print(linebuf)
```

**Comment by fastestdevalive** [comment]
I am not sure. This issue is marked as fixed but JakeWharton/pidcat still doesn't have it. Can we merge this into that as well? :)

**Comment by aancw** [comment]
> works fine in python 3.9.x you just have to edit the last line..
> 
> ```diff
> --  print(linebuf.encode('utf-8'))
> ++  print(linebuf)
> ```

Confirmed work!
